#! Copyright 2021 VMware, Inc.
#! SPDX-License-Identifier: Apache-2.0

#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
kp_default_repository: ""
kp_default_repository_username: ""
kp_default_repository_password: ""

http_proxy: ""
https_proxy: ""
no_proxy: ""

ca_cert_data: ""